title: zhouning blog 
email: 244305150@qq.com
phone: 123456
description: 个人博客 
baseurl: "/znblog" # the subpath of your site, e.g. /blog
url: "https://zhousning.github.io/jekyll-template/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
